# SPDX-FileCopyrightText: 2024 Julia DeMille <me@jdemille.com>
#
# SPDX-License-Identifier: MPL-2.0

[workspace]
members = ["fmod-studio-sys", "fmod-sys", "fsbank-sys", "fmod-build-utils"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
