# SPDX-FileCopyrightText: 2024 Julia DeMille <me@jdemille.com>
#
# SPDX-License-Identifier: MPL-2.0

version = 1
SPDX-PackageName = "fmod-sys"
SPDX-PackageSupplier = "Julia DeMille <me@jdemille.com>"
SPDX-PackageDownloadLocation = "https://sr.ht/~jdemille/fmod.rs"
annotations = []
